/* tslint:disable:max-line-length */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/dashboard',
    },
    {
        id: 'shops',
        title: 'Shops',
        type: 'basic',
        icon: 'heroicons_outline:shopping-bag',
        link: '/store',
    },
    {
        id: 'payment',
        title: 'Payment',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/payment',
    },
    {
        id: 'reports',
        title: 'Reports',
        type: 'basic',
        icon: 'heroicons_outline:document-report',
        link: '/reports',
    },
    {
        id: 'communication',
        title: 'Communication',
        type: 'basic',
        icon: 'heroicons_outline:chat',
        link: '/communication',
    },
    {
        id: 'my-subscription',
        title: 'My Subscription',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/my-subscription',
    },
    {
        id: 'sign-out',
        title: 'Sign Out',
        type: 'basic',
        icon: 'heroicons_outline:logout',
        link: '/sign-out',
    },
    // {
    //     id: 'example',
    //     title: 'Example',
    //     type: 'basic',
    //     icon: 'heroicons_outline:chart-pie',
    //     link: '/example',
    // },
];
export const compactNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/dashboard',
    },
    {
        id: 'shops',
        title: 'Shops',
        type: 'basic',
        icon: 'heroicons_outline:shopping-bag',
        link: '/store',
    },
    {
        id: 'payment',
        title: 'Payment',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/payment',
    },
    {
        id: 'reports',
        title: 'Reports',
        type: 'basic',
        icon: 'heroicons_outline:document-report',
        link: '/reports',
    },
    {
        id: 'communication',
        title: 'Communication',
        type: 'basic',
        icon: 'heroicons_outline:chat',
        link: '/communication',
    },
    {
        id: 'my-subscription',
        title: 'My Subscription',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/my-subscription',
    },
    {
        id: 'sign-out',
        title: 'Sign Out',
        type: 'basic',
        icon: 'heroicons_outline:logout',
        link: '/sign-out',
    },
    // {
    //     id: 'example',
    //     title: 'Example',
    //     type: 'basic',
    //     icon: 'heroicons_outline:chart-pie',
    //     link: '/example',
    // },
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/dashboard',
    },
    {
        id: 'shops',
        title: 'Shops',
        type: 'basic',
        icon: 'heroicons_outline:shopping-bag',
        link: '/store',
    },
    {
        id: 'payment',
        title: 'Payment',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/payment',
    },
    {
        id: 'reports',
        title: 'Reports',
        type: 'basic',
        icon: 'heroicons_outline:document-report',
        link: '/reports',
    },
    {
        id: 'communication',
        title: 'Communication',
        type: 'basic',
        icon: 'heroicons_outline:chat',
        link: '/communication',
    },
    {
        id: 'my-subscription',
        title: 'My Subscription',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/my-subscription',
    },
    {
        id: 'sign-out',
        title: 'Sign Out',
        type: 'basic',
        icon: 'heroicons_outline:logout',
        link: '/sign-out',
    },
    // {
    //     id: 'example',
    //     title: 'Example',
    //     type: 'basic',
    //     icon: 'heroicons_outline:chart-pie',
    //     link: '/example',
    // },
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id: 'dashboard',
        title: 'Dashboard',
        type: 'basic',
        icon: 'heroicons_outline:home',
        link: '/dashboard',
    },
    {
        id: 'shops',
        title: 'Shops',
        type: 'basic',
        icon: 'heroicons_outline:shopping-bag',
        link: '/store',
    },
    {
        id: 'payment',
        title: 'Payment',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/payment',
    },
    {
        id: 'reports',
        title: 'Reports',
        type: 'basic',
        icon: 'heroicons_outline:document-report',
        link: '/reports',
    },
    {
        id: 'communication',
        title: 'Communication',
        type: 'basic',
        icon: 'heroicons_outline:chat',
        link: '/communication',
    },
    {
        id: 'my-subscription',
        title: 'My Subscription',
        type: 'basic',
        icon: 'heroicons_outline:credit-card',
        link: '/my-subscription',
    },
    {
        id: 'sign-out',
        title: 'Sign Out',
        type: 'basic',
        icon: 'heroicons_outline:logout',
        link: '/sign-out',
    },
    // {
    //     id: 'example',
    //     title: 'Example',
    //     type: 'basic',
    //     icon: 'heroicons_outline:chart-pie',
    //     link: '/example',
    // },
];
